from __future__ import annotations
from typing import Protocol
from research_keeper.models import Source

class Index(Protocol):
    def upsert_source(self, source: Source) -> None: ...
    def remove_source(self, slug: str) -> None: ...
    def search_fts(self, query: str, limit: int = 20) -> list[Source]: ...
    def rebuild(self, sources: list[Source]) -> None: ...
