from __future__ import annotations
from typing import Protocol
from research_keeper.models import Source


class Index(Protocol):
    def upsert_source(self, source: Source) -> None: ...
    def remove_source(self, slug: str) -> None: ...
    def search_fts(self, query: str, limit: int = 20) -> list[Source]: ...
    def rebuild(self, sources: list[Source]) -> None: ...
    def sources_for_tag(self, tag_slug: str) -> list[str]: ...
    def tags_for_source(self, source_slug: str) -> list[str]: ...
    def source_content_by_slug(self, slug: str) -> str | None: ...
