from __future__ import annotations
from pathlib import Path
from typing import Protocol
from research_keeper.models import Source

class SourceStore(Protocol):
    def add(self, content: str, metadata: dict) -> Source: ...
    def get(self, slug: str) -> Source | None: ...
    def list(self) -> list[Source]: ...
    def exists_hash(self, hash: str) -> bool: ...
    def source_dir(self, slug: str) -> Path: ...
    def remove(self, slug: str) -> None: ...
